FLASK_APP = "wsgi.py"
FLASK_RUN_HOST = "0.0.0.0"
FLASK_RUN_PORT = 5000
FLASK_ENV = "development"
SECRET_KEY = "secret"
DEGUG = True
# API
API_URL = "/api/v1/"
API_VERSION = 1
# CORS
CORS = "*"
CORS_ORIGIN = "*"
CORS_ALLOW_METHODS = "*"
CORS_ALLOW_HEADERS = "*"
CORS_EXPOSE_HEADERS = "*"

# PATHS
TMP_FOLDERNAME = "tmp"
TEMPLATES_FOLDERNAME = "templates"
STATIC_FOLDERNAME = "static"
IMAGES_FOLDERNAME = "images"
FONTS_FOLDERNAME = "fonts"
